# -*- coding: utf-8 -*-
"""Week_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pgh7CjiiCLcr8blS8AuOCnC5Awyh2kd
"""

#Task 1_1

import matplotlib.pyplot as plt
# example of loading an image with the Keras API
from keras.preprocessing.image import load_img
# load the image
img_path = '/content/drive/MyDrive/Colab Notebooks/Assets/1_Gammar 2021_1_2021_06_03-13-19-23-856.PNG'
img = load_img(img_path)
# report details about the image
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
# show the image using matplotlib
plt.imshow(img)
plt.axis('off') # Turn off axis labels
plt.show()

#Task 1_2

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import array_to_img
# load the image
img_path = '/content/drive/MyDrive/Colab Notebooks/Assets/1_Gammar 2021_1_2021_06_03-13-19-23-856.PNG'
img = load_img(img_path)
print(type(img))
# convert to numpy array
img_array = img_to_array(img)
print(img_array.dtype)
print(img_array.shape)
# convert back to image
img_pil = array_to_img(img_array)
print(type(img))

#Task 1_3

import matplotlib.pyplot as plt
import os
# example of saving an image with the Keras API
from keras.preprocessing.image import load_img
from keras.preprocessing.image import save_img
from keras.preprocessing.image import img_to_array
# load image as as grayscale
img_path = '/content/drive/MyDrive/Colab Notebooks/Assets/1_Gammar 2021_1_2021_06_03-13-19-23-856.PNG'
img = load_img(img_path, color_mode='grayscale')
# convert image to a numpy array
img_array = img_to_array(img)
# save the image with a new filename
save_path_dir = '/content/drive/MyDrive/Colab Notebooks/Assets'
save_filename = 'Task 1_3.jpg'
full_save_path = os.path.join(save_path_dir, save_filename)
save_img(full_save_path, img_array)
# load the image to confirm it was saved correctly
img = load_img(full_save_path)
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
# show the image using matplotlib
plt.imshow(img)
plt.axis('off') # Turn off axis labels
plt.show()

#Task 1_4

from keras.datasets import mnist
(train_images, train_labels), (test_images,
test_labels) = mnist.load_data()
print('Train', train_images.shape,
train_labels.shape)
print('Test', (test_images.shape,
test_labels.shape))
print('Train', train_images.min(),
train_images.max(), train_images.mean(),
train_images.std())
print('Train', test_images.min(),
test_images.max(), test_images.mean(),
test_images.std())

#Task 1_5

from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator
(trainX, trainY), (testX, testY) = mnist.load_data()
width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))
print('Train min=%.3f, max=%.3f' % (trainX.min(), trainX.max()))
print('Test min=%.3f, max=%.3f' % (testX.min(), testX.max()))
datagen = ImageDataGenerator(rescale=1.0/255.0)
train_iterator = datagen.flow(trainX, trainY, batch_size=64)
test_iterator = datagen.flow(testX, testY, batch_size=64)
print('Batches train=%d, test=%d' % (len(train_iterator),
len(test_iterator)))
batchX, batchy = next(train_iterator)
print('Batch shape=%s, min=%.3f, max=%.3f' % (batchX.shape,
batchX.min(), batchX.max()))

#Task 1_6

from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator
(trainX, trainy), (testX, testy) = mnist.load_data()
width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height,
channels))
testX = testX.reshape((testX.shape[0], width, height,
channels))
print('Means train=%.3f, test=%.3f' % (trainX.mean(),
testX.mean()))
datagen = ImageDataGenerator(featurewise_center=True)
datagen.fit(trainX)
print('Data Generator Mean: %.3f' % datagen.mean.item())
iterator = datagen.flow(trainX, trainy, batch_size=64)
batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean())
iterator = datagen.flow(trainX, trainy,
batch_size=len(trainX), shuffle=False)
batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean())

#Task 1_7

from keras.datasets import mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator
(trainX, trainy), (testX, testy) = mnist.load_data()
width, height, channels = trainX.shape[1], trainX.shape[2], 1
trainX = trainX.reshape((trainX.shape[0], width, height, channels))
testX = testX.reshape((testX.shape[0], width, height, channels))
print('Statistics train=%.3f (%.3f), test=%.3f (%.3f)' % (trainX.mean(), trainX.std(),
testX.mean(), testX.std()))
datagen = ImageDataGenerator(featurewise_center=True,
featurewise_std_normalization=True)
datagen.fit(trainX)
print('Data Generator mean=%.3f, std=%.3f' % (datagen.mean.item(),
datagen.std.item()))
iterator = datagen.flow(trainX, trainy, batch_size=64)
batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean(), batchX.std())
iterator = datagen.flow(trainX, trainy, batch_size=len(trainX), shuffle=False)
batchX, batchy = next(iterator)
print(batchX.shape, batchX.mean(), batchX.std())

"""# New section"""
